spring.application.name=nursery

spring.datasource.url=jdbc:mysql://localhost:3306/nursery_db
spring.datasource.username=USER_NAME
spring.datasource.password=PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080

cloudinary.cloud_name = UR_CLOUD_NAME
cloudinary.api_key = API_KEY
cloudinary.api_secret = API_SECRECT

